pimcore_data_hub:
    configurations:
        user-info:
            general:
                type: graphql
                path: null
                name: user-info
                modificationDate: 1684808000
                createDate: 1684808000
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
